CREATE DATABASE CadastroUsuarios;
GO

USE CADASTROUSUARIOS;
GO

CREATE TABLE Pessoa (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Nome NVARCHAR(100) NOT NULL,
    Cpf CHAR(11) NOT NULL UNIQUE,
    Telefone NVARCHAR(20) NOT NULL
);
GO

CREATE TABLE Endereco (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Logradouro NVARCHAR(100) NOT NULL,
    Numero NVARCHAR(10) NOT NULL,
    Complemento NVARCHAR(50),
    Bairro NVARCHAR(50) NOT NULL,
    Cidade NVARCHAR(50) NOT NULL,
    Estado CHAR(2) NOT NULL,
    Cep CHAR(8) NOT NULL,
    PessoaId UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_Endereco_Pessoa FOREIGN KEY (PessoaId) REFERENCES Pessoa(Id)
);
GO

CREATE TABLE Usuario (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    Senha NVARCHAR(255) NOT NULL,
    TipoUsuario INT NOT NULL,
    PessoaId UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_Usuario_Pessoa FOREIGN KEY (PessoaId) REFERENCES Pessoa(Id)
);
GO